server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.4:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: DongChunFeng202107
    hikari:
      connection-timeout: 30000  #等待连接池分配连接的最大时长
      minimum-idle: 5   # 最小连接数
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000 #连接超时的最大时长  毫秒 超时则被释放
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000 #连接的生命时长
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000  #文件上传大小限制500k
      max-request-size: 512000  #请求大小限制500k
mybatis:
  type-aliases-package: com.itzixue.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.itzixue.my.mapper.MyMapper
  not-empty: false  #在进行数据库操作的时候 判断表达式username!=null 是否追加 username!=''
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true